# Generated by Django 6.0.7 on 2026-08-02 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('folder', 'Ordner'), ('file', 'Notiz')], default='file', max_length=10)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='knowledgebase.knowledgeitem')),
            ],
            options={
                'verbose_name': 'Knowledge Base Item',
                'verbose_name_plural': 'Knowledge Base Items',
                'ordering': ['name'],
            },
        ),
    ]
