# Generated by Django 6.0.7 on 2026-08-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garmin_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('activity_type', models.CharField(blank=True, max_length=100)),
                ('start_time', models.DateTimeField()),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('distance_m', models.FloatField(blank=True, null=True)),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('steps', models.PositiveIntegerField(blank=True, null=True)),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
                ('resting_heart_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sleep_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Daily Stats',
                'ordering': ['-date'],
            },
        ),
    ]
