# Generated by Django 6.0.7 on 2026-08-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
